Servers:
  1: 
    Address: 127.0.0.1
    Port: 1234
  2: 
    Address: 127.0.0.1
    Port: 1235
  3: 
    Address: 127.0.0.1
    Port: 1236
  4: 
    Address: 127.0.0.1
    Port: 1237
Timeout:
  Min_ms: 150
  Max_ms: 300
NVStateFilenameBase: raftstate