Host:
  Address: 192.168.88.106
  Port: 4040
Players:
  Player0:
    Address: 192.168.88.101 # don't use localhost or 127.0.0.1 as this won't map correctly on remote players!, it is a pain in WSL though...
    Port: 1234
  Player1:
    Address: 192.168.88.102
    Port: 1234
  Player2:
    Address: 192.168.88.103
    Port: 1234
  Player3:
    Address: 192.168.88.104
    Port: 1234
